from fpdf import FPDF
from datetime import datetime


_UNICODE_MAP = {
    "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
    "\u2013": "-", "\u2014": "--", "\u2026": "...",
    "\u2022": "*", "\u00b7": ".",
}


def _safe(text: str, max_len: int = 0) -> str:
    text = str(text)
    for k, v in _UNICODE_MAP.items():
        text = text.replace(k, v)
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    if max_len and len(text) > max_len:
        text = text[:max_len] + "..."
    return text


class CredibilityReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_fill_color(20, 26, 60)
        self.set_text_color(220, 230, 255)
        self.cell(0, 13, "  AI Credibility Assessment Report", new_x="LMARGIN", new_y="NEXT", fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f"Generated by AI Misinformation Monitor  |  Page {self.page_no()}", align="C")

    def section_title(self, title: str, rgb=(50, 90, 200)):
        self.ln(2)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*rgb)
        self.cell(0, 8, _safe(title), new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*rgb)
        self.line(self.get_x(), self.get_y(), self.get_x() + 170, self.get_y())
        self.ln(3)
        self.set_text_color(0, 0, 0)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, _safe(text))
        self.ln(2)

    def bullet_list(self, items: list, rgb=(30, 30, 30)):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*rgb)
        for item in items:
            self.cell(8, 6, chr(149))
            self.multi_cell(0, 6, _safe(str(item)), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def verdict_box(self, verdict: str, conf_level: str, ml_label: str, ml_conf: float):
        if "CREDIBLE" in verdict:
            fill, border, txt = (6, 78, 59), (16, 185, 129), (110, 231, 183)
        elif "FAKE" in verdict:
            fill, border, txt = (69, 10, 10), (239, 68, 68), (252, 165, 165)
        else:
            fill, border, txt = (69, 26, 3), (245, 158, 11), (252, 211, 77)

        self.set_fill_color(*fill)
        self.set_draw_color(*border)
        box_h = 28
        x0, y0 = self.get_x(), self.get_y()
        self.rect(x0, y0, 170, box_h, style="FD")
        self.set_xy(x0 + 5, y0 + 5)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*txt)
        self.cell(90, 8, _safe(f"Verdict: {verdict}"))
        self.set_font("Helvetica", "", 10)
        self.set_text_color(200, 200, 200)
        self.cell(0, 8, _safe(f"Confidence: {conf_level}  |  ML: {ml_label} ({ml_conf}%)"), new_x="LMARGIN", new_y="NEXT")
        self.set_y(y0 + box_h + 6)
        self.set_text_color(0, 0, 0)


def generate_pdf(article_text: str, prediction: dict, analysis: dict, retrieval: dict) -> bytes:
    pdf = CredibilityReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_text_color(0, 0, 0)

    ca = analysis.get("confidence_assessment", {})
    pdf.verdict_box(
        ca.get("overall_verdict", "UNCERTAIN"),
        ca.get("confidence_level", "LOW"),
        prediction["label"],
        prediction["confidence"],
    )

    pdf.section_title("1. Article Summary")
    pdf.body_text(analysis.get("article_summary", "N/A"))

    pdf.section_title("2. Credibility Indicators")
    ci = analysis.get("credibility_indicators", {})
    if ci.get("positive"):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Supporting indicators:", new_x="LMARGIN", new_y="NEXT")
        pdf.bullet_list(ci["positive"], rgb=(0, 120, 0))
    if ci.get("negative"):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Red flags:", new_x="LMARGIN", new_y="NEXT")
        pdf.bullet_list(ci["negative"], rgb=(180, 0, 0))

    pdf.section_title("3. Risk Factors")
    rf = analysis.get("risk_factors", [])
    pdf.bullet_list(rf) if rf else pdf.body_text("No significant risk factors identified.")

    pdf.section_title("4. Cross-Source Verification")
    pdf.body_text(analysis.get("cross_source_verification", "N/A"))
    ss = analysis.get("supporting_sources", [])
    if ss:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Referenced sources:", new_x="LMARGIN", new_y="NEXT")
        pdf.bullet_list(ss)

    pdf.section_title("5. Confidence Assessment")
    pdf.body_text(ca.get("reasoning", "N/A"))

    pdf.section_title("6. Retrieved Fact-Check Sources")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 5, f"Keywords: {_safe(retrieval.get('keywords_used', ''))}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)
    for src in retrieval.get("sources", []):
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, _safe(src.get("title", "")[:80]), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 5, _safe(src.get("snippet", "")[:200]))
        url = src.get("url", "")
        if url and url != "N/A":
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, _safe(url[:100]), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)

    pdf.section_title("7. Article Excerpt Analyzed")
    excerpt = article_text[:500] + ("..." if len(article_text) > 500 else "")
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 5, _safe(excerpt))
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    pdf.section_title("8. Ethical Disclaimer & Warnings", rgb=(160, 60, 0))
    pdf.set_fill_color(255, 248, 235)
    pdf.set_draw_color(200, 120, 0)
    disclaimer = _safe(analysis.get(
        "ethical_disclaimer",
        "This report is generated by an AI system and should not be used as the "
        "sole basis for judgments about content credibility.",
    ))
    box_h = 10 + max(2, len(disclaimer) // 80 + 1) * 6
    x0, y0 = pdf.get_x(), pdf.get_y()
    pdf.rect(x0, y0, 170, box_h, style="FD")
    pdf.set_xy(x0 + 4, y0 + 4)
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(162, 5, disclaimer)
    pdf.set_y(y0 + box_h + 4)

    warning = analysis.get("misinformation_warning", "")
    if warning:
        warn_text = _safe(f"WARNING: {warning}")
        pdf.set_fill_color(255, 235, 235)
        pdf.set_draw_color(200, 0, 0)
        box_h = 10 + max(2, len(warn_text) // 80 + 1) * 6
        x0, y0 = pdf.get_x(), pdf.get_y()
        pdf.rect(x0, y0, 170, box_h, style="FD")
        pdf.set_xy(x0 + 4, y0 + 4)
        pdf.set_text_color(180, 0, 0)
        pdf.set_font("Helvetica", "B", 9)
        pdf.multi_cell(162, 5, warn_text)
        pdf.set_text_color(0, 0, 0)

    return bytes(pdf.output())